### ISSUE TITLE
Conflict with MSCORLIB

### ISSUE THREAD

**Issue by andersleet** [piedoom/TumblrSharp#22] opened 2018-03-10 04:02 UTC
`The type 'HMACSHA1' exists in both 'bouncy_castle_hmac_sha_pcl, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	SocialMediaPoster`

I cannot reference MSCORLIB in the other section of my application that relies on this. Is there a specific reason why you (or the developer) implemented bouncy_castle's `System.Security.Cryptography.HMACSHA1` that causes conflicts with baked-in references?

**Comment by piedoom** [comment] 2018-03-10 16:13
While I'm okay at programming in C#, I'm very unfamiliar with the language's tooling.  I apologize but I'm unsure what is causing this issue or how to resolve it (but certainly will accept any fixes from the community).

**Comment by Cataurus** [comment] 2018-04-06 02:06
The problem is the type of library as portable, as pcl. This makes the integration of the BouncyCastle.hmacsha.lib necessary. A port to .NetStandard no longer needs them. A conversion is available in the fork from this project in the [dev branch](https://github.com/Cataurus/TumblrSharp/tree/dev).

**Comment by Cataurus** [comment] 2018-04-21 03:50
Fixed by last merged

**Closed as completed by Cataurus** 2018-04-21 03:50 UTC
